# Generated by Django 3.0 on 2023-03-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
                ('types', models.CharField(max_length=50)),
                ('direct', models.CharField(max_length=50)),
                ('boxoffice', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'boxOffice',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('favourable', models.IntegerField()),
                ('differ', models.IntegerField()),
                ('general', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
